import {mkdir, writeFile} from 'node:fs/promises';
import path from 'node:path';
import type {TimelineIR} from '../ir.js';
import type {FrameScriptPlugin, RemotionPluginLayer} from '../plugins.js';
import type {FrameScriptSourceMap} from '../source-map.js';
import type {MediaProbeReport} from '../media.js';

const REMOTION_VERSION = '4.0.533';

export interface RemotionProjectOptions {
  readonly outputDirectory: string;
  readonly projectName?: string;
  readonly plugins?: readonly FrameScriptPlugin[];
  readonly sourceMap?: FrameScriptSourceMap;
  readonly mediaManifest?: MediaProbeReport;
}

export interface GeneratedProject {
  readonly directory: string;
  readonly files: readonly string[];
}

export async function generateRemotionProject(
  ir: TimelineIR,
  options: RemotionProjectOptions,
): Promise<GeneratedProject> {
  const directory = path.resolve(options.outputDirectory);
  const sourceDirectory = path.join(directory, 'src');
  const publicDirectory = path.join(directory, 'public');
  await mkdir(sourceDirectory, {recursive: true});
  await mkdir(publicDirectory, {recursive: true});

  const pluginLayers = collectPluginLayers(ir, options.plugins ?? []);
  const sourceMap = options.sourceMap ?? emptySourceMap();
  const files = new Map<string, string>([
    ['package.json', projectPackage(options.projectName ?? 'framescript-video', pluginLayers)],
    ['tsconfig.json', projectTsconfig()],
    ['remotion.config.ts', remotionConfig()],
    ['src/program.generated.ts', generatedProgram(ir)],
    ['framescript.map.json', `${JSON.stringify(sourceMap, null, 2)}\n`],
    ['media-manifest.json', `${JSON.stringify(options.mediaManifest ?? emptyMediaManifest(), null, 2)}\n`],
    ['src/source-map.generated.ts', generatedSourceMap(sourceMap)],
    ['src/fonts.generated.ts', generatedFonts(ir)],
    ['src/FrameScriptRuntimeBoundary.tsx', runtimeBoundarySource()],
    ['src/FrameScriptComposition.tsx', runtimeSource(pluginLayers)],
    ['src/Root.tsx', rootSource()],
    ['src/index.ts', entrySource()],
    ['README.md', generatedReadme()],
  ]);

  await Promise.all([...files].map(async ([relative, contents]) => {
    const destination = path.join(directory, relative);
    await mkdir(path.dirname(destination), {recursive: true});
    await writeFile(destination, contents, 'utf8');
  }));
  return {directory, files: [...files.keys()]};
}

function projectPackage(name: string, pluginLayers: ReadonlyMap<string, RemotionPluginLayer>): string {
  const pluginDependencies = Object.fromEntries(
    [...pluginLayers.values()].map(({packageName, packageVersion}) => [packageName, packageVersion]),
  );
  return `${JSON.stringify({
    name: sanitizePackageName(name),
    version: '0.0.0',
    private: true,
    type: 'module',
    scripts: {
      studio: 'remotion studio src/index.ts',
      render: 'remotion render src/index.ts',
      still: 'remotion still src/index.ts',
      check: 'tsc --noEmit',
    },
    dependencies: {
      '@remotion/cli': REMOTION_VERSION,
      '@remotion/fonts': REMOTION_VERSION,
      '@remotion/media': REMOTION_VERSION,
      remotion: REMOTION_VERSION,
      react: '19.2.0',
      'react-dom': '19.2.0',
      ...pluginDependencies,
    },
    devDependencies: {
      '@types/react': '19.2.2',
      '@types/react-dom': '19.2.2',
      typescript: '5.9.3',
    },
  }, null, 2)}\n`;
}

function projectTsconfig(): string {
  return `${JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'Bundler',
      lib: ['ES2022', 'DOM'],
      jsx: 'react-jsx',
      strict: true,
      noEmit: true,
      skipLibCheck: true,
    },
    include: ['src', 'remotion.config.ts'],
  }, null, 2)}\n`;
}

function remotionConfig(): string {
  return `import {Config} from '@remotion/cli/config';

Config.setVideoImageFormat('jpeg');
Config.setOverwriteOutput(true);
`;
}

function generatedProgram(ir: TimelineIR): string {
  return `// Generated by FrameScript. Do not edit by hand.\nexport default ${JSON.stringify(ir, null, 2)} as const;\n`;
}

function generatedSourceMap(sourceMap: FrameScriptSourceMap): string {
  return `// Generated by FrameScript. Do not edit by hand.\nexport default ${JSON.stringify(sourceMap, null, 2)} as const;\n`;
}

function runtimeBoundarySource(): string {
  return `import {Component, type ErrorInfo, type ReactNode} from 'react';

export type FrameScriptSourceMap = {
  readonly sources: readonly {readonly id: string; readonly path: string}[];
  readonly mappings: Readonly<Record<string, {
    readonly source: string;
    readonly start: {readonly line: number; readonly column: number};
  }>>;
};

const sourceLocation = (sourceMap: FrameScriptSourceMap, key: string): string | undefined => {
  let candidate = key;
  while (candidate.length > 0) {
    const mapping = sourceMap.mappings[candidate];
    const source = mapping ? sourceMap.sources.find(({id}) => id === mapping.source) : undefined;
    if (mapping && source) return \`\${source.path}:\${mapping.start.line}:\${mapping.start.column}\`;
    const separator = candidate.lastIndexOf('/');
    if (separator < 0) break;
    candidate = candidate.slice(0, separator);
  }
  return undefined;
};

export const remapFrameScriptError = (error: unknown, sourceKey: string, sourceMap: FrameScriptSourceMap): Error => {
  const original = error instanceof Error ? error : new Error(String(error));
  if (original.name === 'FrameScriptRuntimeError') return original;
  const location = sourceLocation(sourceMap, sourceKey);
  const suffix = location ? \`\\nFrameScript source: \${location} [\${sourceKey}]\` : \`\\nFrameScript source key: \${sourceKey}\`;
  const remapped = new Error(\`\${original.message}\${suffix}\`, {cause: original});
  remapped.name = 'FrameScriptRuntimeError';
  return remapped;
};

type Props = {
  readonly sourceKey: string;
  readonly sourceMap: FrameScriptSourceMap;
  readonly children: ReactNode;
};
type State = {readonly error?: unknown};

export class FrameScriptRuntimeBoundary extends Component<Props, State> {
  public override state: State = {};

  public static getDerivedStateFromError(error: unknown): State {
    return {error};
  }

  public override componentDidCatch(_error: unknown, _info: ErrorInfo): void {
    // The next render rethrows a source-enriched error to Remotion's renderer.
  }

  public override render(): ReactNode {
    if (this.state.error !== undefined) {
      throw remapFrameScriptError(this.state.error, this.props.sourceKey, this.props.sourceMap);
    }
    return this.props.children;
  }
}
`;
}

function generatedFonts(ir: TimelineIR): string {
  if (ir.fonts.length === 0) return '// Generated by FrameScript. No declared fonts.\n';
  const entries = ir.fonts.map((font) => {
    const source = resolveDeclaredSource(font.source, ir);
    const url = /^(?:https?:|data:|blob:)/u.test(source) ? JSON.stringify(source) : `staticFile(${JSON.stringify(source)})`;
    return `loadFont({family: ${JSON.stringify(font.family)}, url: ${url}, weight: ${JSON.stringify(String(font.weight))}, style: ${JSON.stringify(font.style)}});`;
  });
  return `// Generated by FrameScript. Do not edit by hand.
import {loadFont} from '@remotion/fonts';
import {staticFile} from 'remotion';

${entries.join('\n')}
`;
}

function entrySource(): string {
  return `import {registerRoot} from 'remotion';
import {FrameScriptRoot} from './Root';

registerRoot(FrameScriptRoot);
`;
}

function rootSource(): string {
  return `import './fonts.generated';
import type {FC} from 'react';
import {Composition} from 'remotion';
import program from './program.generated';
import sourceMap from './source-map.generated';
import {FrameScriptComposition} from './FrameScriptComposition';

export const FrameScriptRoot: FC = () => (
  <>
    {program.compositions.map((composition) => (
      <Composition
        key={composition.id}
        id={composition.id}
        component={FrameScriptComposition}
        durationInFrames={composition.durationInFrames}
        fps={composition.fps}
        width={composition.width}
        height={composition.height}
        defaultProps={{composition, assets: program.assets, sourceMap}}
      />
    ))}
  </>
);
`;
}

function runtimeSource(pluginLayers: ReadonlyMap<string, RemotionPluginLayer>): string {
  const pluginImports = [...pluginLayers.entries()].map(([type, entry], index) =>
    `import {${entry.exportName} as FrameScriptPlugin${index}} from ${JSON.stringify(entry.packageName)}; // ${type}`,
  ).join('\n');
  const pluginEntries = [...pluginLayers.keys()].map((type, index) =>
    `${JSON.stringify(type)}: FrameScriptPlugin${index}`,
  ).join(',\n  ');
  return `import type {CSSProperties, FC, ReactNode} from 'react';
import {Audio, Video} from '@remotion/media';
import {
  AbsoluteFill,
  Easing,
  Img,
  Sequence,
  interpolate,
  interpolateColors,
  staticFile,
  useCurrentFrame,
} from 'remotion';
import {FrameScriptRuntimeBoundary, type FrameScriptSourceMap} from './FrameScriptRuntimeBoundary';
${pluginImports}

type Value = string | number | boolean | readonly Value[];
type Asset = {readonly id: string; readonly source: string; readonly publicPath?: string};
type Keyframe = {readonly frame: number; readonly value: Value; readonly easing: string};
type Animation = {readonly property: string; readonly keyframes: readonly Keyframe[]};
type Layer = {
  readonly id: string;
  readonly type: string;
  readonly plugin?: string;
  readonly from: number;
  readonly duration: number;
  readonly props: Readonly<Record<string, Value>>;
  readonly animations: readonly Animation[];
  readonly children: readonly Layer[];
};

type PluginLayerComponent = FC<{readonly layer: Layer; readonly props: Readonly<Record<string, Value>>; readonly frame: number}>;
const pluginLayers: Readonly<Record<string, PluginLayerComponent>> = {
  ${pluginEntries}
};
type CompositionIR = {
  readonly id: string;
  readonly width: number;
  readonly height: number;
  readonly fps: number;
  readonly durationInFrames: number;
  readonly background: string;
  readonly layers: readonly Layer[];
};

const easing: Readonly<Record<string, (value: number) => number>> = {
  linear: Easing.linear,
  'in-quad': Easing.in(Easing.quad),
  'out-quad': Easing.out(Easing.quad),
  'in-out-quad': Easing.inOut(Easing.quad),
  'in-cubic': Easing.in(Easing.cubic),
  'out-cubic': Easing.out(Easing.cubic),
  'in-out-cubic': Easing.inOut(Easing.cubic),
  'in-quart': Easing.in(Easing.poly(4)),
  'out-quart': Easing.out(Easing.poly(4)),
  'in-out-quart': Easing.inOut(Easing.poly(4)),
  'in-back': Easing.in(Easing.back(1.70158)),
  'out-back': Easing.out(Easing.back(1.70158)),
  'in-out-back': Easing.inOut(Easing.back(1.70158)),
  'step-start': (value) => value <= 0 ? 0 : 1,
  'step-end': (value) => value < 1 ? 0 : 1,
};

const asset = (source: string, assets: readonly Asset[]): string => {
  const declared = source.startsWith('asset:') ? assets.find(({id}) => id === source.slice(6)) : undefined;
  const resolved = declared?.publicPath ?? declared?.source ?? source;
  return /^(?:https?:|data:|blob:)/u.test(resolved)
    ? resolved
    : staticFile(resolved.replace(/^\\/?public\\//u, ''));
};

const numericUnit = (value: string): {number: number; unit: string} | null => {
  const match = /^(-?\\d+(?:\\.\\d+)?)(.*)$/u.exec(value);
  return match ? {number: Number(match[1]), unit: match[2] ?? ''} : null;
};

const trackValue = (frame: number, track: Animation): Value => {
  const frames = track.keyframes;
  if (frame <= frames[0]!.frame) return frames[0]!.value;
  if (frame >= frames[frames.length - 1]!.frame) return frames[frames.length - 1]!.value;
  let index = 0;
  while (index < frames.length - 2 && frame > frames[index + 1]!.frame) index += 1;
  const left = frames[index]!;
  const right = frames[index + 1]!;
  const options = {
    easing: easing[left.easing] ?? Easing.linear,
    extrapolateLeft: 'clamp' as const,
    extrapolateRight: 'clamp' as const,
  };

  if (typeof left.value === 'number' && typeof right.value === 'number') {
    return interpolate(frame, [left.frame, right.frame], [left.value, right.value], options);
  }
  if (typeof left.value === 'string' && typeof right.value === 'string') {
    if (/^(?:#|rgb|hsl)/u.test(left.value) && /^(?:#|rgb|hsl)/u.test(right.value)) {
      return interpolateColors(frame, [left.frame, right.frame], [left.value, right.value]);
    }
    const leftUnit = numericUnit(left.value);
    const rightUnit = numericUnit(right.value);
    if (leftUnit && rightUnit && leftUnit.unit === rightUnit.unit) {
      const amount = interpolate(frame, [left.frame, right.frame], [leftUnit.number, rightUnit.number], options);
      return \`\${amount}\${leftUnit.unit}\`;
    }
  }
  return frame < right.frame ? left.value : right.value;
};

const resolveProps = (layer: Layer, frame: number): Record<string, Value> => {
  const result: Record<string, Value> = {...layer.props};
  for (const animation of layer.animations) result[animation.property] = trackValue(frame, animation);
  return result;
};

const number = (value: Value | undefined, fallback: number): number =>
  typeof value === 'number' ? value : typeof value === 'string' ? Number.parseFloat(value) : fallback;

const cssSize = (value: Value | undefined, fallback?: string | number): string | number | undefined => {
  if (typeof value === 'number') return value;
  if (typeof value !== 'string') return fallback;
  return value.endsWith('pct') ? \`\${value.slice(0, -3)}%\` : value;
};

const layerStyle = (props: Readonly<Record<string, Value>>, type: Layer['type']): CSSProperties => {
  const x = cssSize(props.x, 0);
  const y = cssSize(props.y, 0);
  const rotate = cssSize(props.rotate, '0deg');
  const scale = number(props.scale, 1);
  const radius = type === 'circle' ? '50%' : cssSize(props.radius, 0);
  const shadow = Array.isArray(props.shadow)
    ? props.shadow.map(String).join(' ')
    : undefined;
  return {
    position: 'absolute',
    left: x,
    top: y,
    width: cssSize(props.width, type === 'group' ? '100%' : undefined),
    height: cssSize(props.height, type === 'group' ? '100%' : undefined),
    opacity: number(props.opacity, 1),
    transform: \`translate(-50%, -50%) rotate(\${rotate}) scale(\${scale})\`,
    transformOrigin: 'center center',
    background: String(props.fill ?? 'transparent'),
    color: String(props.color ?? '#ffffff'),
    borderRadius: radius,
    border: props.stroke ? \`\${cssSize(props.strokeWidth, 1)} solid \${String(props.stroke)}\` : undefined,
    boxShadow: shadow,
    filter: props.blur ? \`blur(\${cssSize(props.blur)})\` : undefined,
    overflow: (props.overflow as CSSProperties['overflow']) ?? 'visible',
    fontSize: cssSize(props.fontSize),
    fontWeight: props.fontWeight as CSSProperties['fontWeight'],
    fontFamily: props.fontFamily as string | undefined,
    fontStyle: props.fontStyle as CSSProperties['fontStyle'],
    lineHeight: props.lineHeight as CSSProperties['lineHeight'],
    letterSpacing: cssSize(props.letterSpacing),
    textAlign: props.textAlign as CSSProperties['textAlign'],
    padding: cssSize(props.padding),
    display: type === 'group' ? 'flex' : undefined,
    flexDirection: props.direction as CSSProperties['flexDirection'],
    gap: cssSize(props.gap),
    alignItems: props.align as CSSProperties['alignItems'],
    justifyContent: props.justify as CSSProperties['justifyContent'],
    whiteSpace: type === 'text' ? 'pre-wrap' : undefined,
  };
};

const fadeVolume = (frame: number, duration: number, props: Readonly<Record<string, Value>>): number => {
  const base = number(props.volume, 1);
  const fadeIn = number(props.fadeIn, 0);
  const fadeOut = number(props.fadeOut, 0);
  const incoming = fadeIn > 0 ? interpolate(frame, [0, fadeIn], [0, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'}) : 1;
  const outgoing = fadeOut > 0 ? interpolate(frame, [duration - fadeOut, duration], [1, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'}) : 1;
  return base * incoming * outgoing;
};

const duckVolume = (frame: number, layer: Layer, target: Layer | undefined, props: Readonly<Record<string, Value>>): number => {
  if (!target) return 1;
  const globalFrame = frame + layer.from;
  const amount = number(props.duckAmount, 0.25);
  const attack = Math.max(0, number(props.duckAttack, 0));
  const release = Math.max(0, number(props.duckRelease, 0));
  const start = target.from;
  const end = target.from + target.duration;
  if (globalFrame < start) return 1;
  if (attack > 0 && globalFrame < start + attack) {
    return interpolate(globalFrame, [start, start + attack], [1, amount], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});
  }
  if (globalFrame < end) return amount;
  if (release > 0 && globalFrame < end + release) {
    return interpolate(globalFrame, [end, end + release], [amount, 1], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});
  }
  return 1;
};

const keyPart = (value: string): string => encodeURIComponent(value);

const LayerContent: FC<{
  readonly layer: Layer;
  readonly assets: readonly Asset[];
  readonly sourceKey: string;
  readonly sourceMap: FrameScriptSourceMap;
  readonly duckTarget?: Layer;
}> = ({layer, assets, sourceKey, sourceMap, duckTarget}) => {
  const frame = useCurrentFrame();
  const props = resolveProps(layer, frame);
  const style = layerStyle(props, layer.type);
  let content: ReactNode = null;
  switch (layer.type) {
    case 'text': content = <div style={style}>{String(props.text ?? '')}</div>; break;
    case 'rect':
    case 'circle': content = <div style={style} />; break;
    case 'image': content = <Img src={asset(String(props.src), assets)} style={{...style, objectFit: props.objectFit as CSSProperties['objectFit']}} />; break;
    case 'video': content = <Video src={asset(String(props.src), assets)} trimBefore={number(props.trimStart, 0)} trimAfter={props.trimEnd === undefined ? undefined : number(props.trimEnd, 0)} volume={fadeVolume(frame, layer.duration, props)} muted={Boolean(props.muted)} playbackRate={number(props.playbackRate, 1)} loop={Boolean(props.loop)} style={{...style, objectFit: props.objectFit as CSSProperties['objectFit']}} />; break;
    case 'audio': content = <Audio src={asset(String(props.src), assets)} trimBefore={number(props.trimStart, 0)} trimAfter={props.trimEnd === undefined ? undefined : number(props.trimEnd, 0)} volume={fadeVolume(frame, layer.duration, props) * duckVolume(frame, layer, duckTarget, props)} muted={Boolean(props.muted)} playbackRate={number(props.playbackRate, 1)} loop={Boolean(props.loop)} />; break;
    case 'group': content = <div style={style}>{layer.children.map((child) => <LayerNode key={child.id} layer={child} assets={assets} sourceKey={\`\${sourceKey}/layer/\${keyPart(child.id)}\`} sourceMap={sourceMap} />)}</div>; break;
    default: {
      const Plugin = pluginLayers[layer.type];
      content = Plugin ? <Plugin layer={layer} props={props} frame={frame} /> : null;
    }
  }
  return <>{content}</>;
};

const LayerNode: FC<{
  readonly layer: Layer;
  readonly assets: readonly Asset[];
  readonly sourceKey: string;
  readonly sourceMap: FrameScriptSourceMap;
  readonly duckTarget?: Layer;
}> = ({layer, assets, sourceKey, sourceMap, duckTarget}) => (
  <FrameScriptRuntimeBoundary sourceKey={sourceKey} sourceMap={sourceMap}>
    <Sequence name={layer.id} from={layer.from} durationInFrames={layer.duration} layout="none">
      <LayerContent layer={layer} assets={assets} sourceKey={sourceKey} sourceMap={sourceMap} duckTarget={duckTarget} />
    </Sequence>
  </FrameScriptRuntimeBoundary>
);

export const FrameScriptComposition: FC<{
  readonly composition: CompositionIR;
  readonly assets: readonly Asset[];
  readonly sourceMap: FrameScriptSourceMap;
}> = ({composition, assets, sourceMap}) => {
  const compositionKey = \`composition/\${keyPart(composition.id)}\`;
  return (
    <FrameScriptRuntimeBoundary sourceKey={compositionKey} sourceMap={sourceMap}>
      <AbsoluteFill style={{backgroundColor: composition.background, overflow: 'hidden'}}>
        {composition.layers.map((layer) => <LayerNode key={layer.id} layer={layer} assets={assets} sourceKey={\`\${compositionKey}/layer/\${keyPart(layer.id)}\`} sourceMap={sourceMap} duckTarget={typeof layer.props.duckUnder === 'string' ? composition.layers.find(({id}) => id === layer.props.duckUnder) : undefined} />)}
      </AbsoluteFill>
    </FrameScriptRuntimeBoundary>
  );
};
`;
}

function generatedReadme(): string {
  return `# Generated FrameScript Remotion project

This directory is generated. Put media referenced by relative \`src\` values in \`public/\`.

\`\`\`sh
npm install
npm run studio
npm run render -- <CompositionId> out/video.mp4
\`\`\`

Regenerate from the FrameScript source instead of editing \`program.generated.ts\`.
Runtime failures are remapped through \`framescript.map.json\` to the original FrameScript declaration.
Probed media metadata and cache identities are recorded in \`media-manifest.json\`.
Review the current Remotion license before production use.
`;
}

function sanitizePackageName(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9._-]+/gu, '-').replace(/^-+|-+$/gu, '') || 'framescript-video';
}

function collectPluginLayers(ir: TimelineIR, plugins: readonly FrameScriptPlugin[]): ReadonlyMap<string, RemotionPluginLayer> {
  const result = new Map<string, RemotionPluginLayer>();
  for (const plugin of plugins) {
    for (const [type, contribution] of Object.entries(plugin.remotion ?? {})) {
      if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(contribution.exportName)) {
        throw new Error(`Remotion export '${contribution.exportName}' for '${type}' is not a JavaScript identifier.`);
      }
      if (/^[~^]/u.test(contribution.packageVersion)) {
        throw new Error(`Plugin package '${contribution.packageName}' must use an exact version.`);
      }
      result.set(type, contribution);
    }
  }
  const visit = (layer: import('../ir.js').IRLayer): void => {
    if (layer.plugin && !result.has(layer.type)) {
      throw new Error(`Plugin layer '${layer.type}' has no Remotion renderer contribution.`);
    }
    for (const child of layer.children) visit(child);
  };
  for (const composition of ir.compositions) for (const layer of composition.layers) visit(layer);
  return result;
}

function resolveDeclaredSource(source: string, ir: TimelineIR): string {
  if (!source.startsWith('asset:')) return source;
  const asset = ir.assets.find(({id}) => id === source.slice(6));
  if (!asset) throw new Error(`Font references missing asset '${source.slice(6)}'.`);
  return asset.publicPath ?? asset.source;
}

function emptySourceMap(): FrameScriptSourceMap {
  return {
    schema: 'framescript-source-map',
    version: 1,
    entry: '<unknown>',
    sources: [],
    mappings: {},
  };
}

function emptyMediaManifest(): MediaProbeReport {
  return {
    schema: 'framescript-media-manifest',
    version: 1,
    probedAssets: 0,
    cacheHits: 0,
    warnings: [],
    assets: [],
  };
}
